apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
  replicas: 1
  command:
    - dragonfly
    - --logtostderr